/**
 * ARDENLEE POKER LEAGUE - Data File
 * Season 20 | Peachtree City, GA
 * Last updated: after Event 12 (2026-07-16)
 */

const LEAGUE = {
  name: "Ardenlee Poker League",
  season: 20,
  host: "Tod Ellison",
  location: "Peachtree City, GA",

  announcements: [
    { active: true, type: "special", icon: "🔥", text: "Karey Koscevic wins Event 13 with 6 straight final-table eliminations! The OG was on fire! Next up: Event 14 — August 25th at Tod's. RSVP below!" },
  ],

  schedule: [
    { date: "2026-02-19", label: "Event 1",               type: "regular",    completed: true  },
    { date: "2026-03-05", label: "Event 2",               type: "regular",    completed: true  },
    { date: "2026-03-19", label: "Event 3",               type: "regular",    completed: true  },
    { date: "2026-04-02", label: "Event 4",               type: "regular",    completed: true  },
    { date: "2026-04-16", label: "Event 5",               type: "regular",    completed: true  },
    { date: "2026-04-30", label: "Event 6",               type: "regular",    completed: true  },
    { date: "2026-05-14", label: "Event 7",               type: "regular",    completed: true  },
    { date: "2026-05-19", label: "Event 8",               type: "regular",    completed: true  },
    { date: "2026-06-04", label: "Event 9",               type: "regular",    completed: true  },
    { date: "2026-06-18", label: "Event 10",              type: "regular",    completed: true  },
    { date: "2026-07-02", label: "Event 11",              type: "regular",    completed: true  },
    { date: "2026-07-16", label: "Event 12",              type: "regular",    completed: true  },
    { date: "2026-07-25", label: "Mid-Season Tournament", type: "tournament", completed: true  },
    { date: "2026-08-11", label: "Event 13",              type: "regular",    completed: true  },
    { date: "2026-08-25", label: "Event 14",              type: "regular",    completed: false },
    { date: "2026-09-08", label: "Event 15",              type: "regular",    completed: false },
    { date: "2026-09-22", label: "Season Final",          type: "final",      completed: false },
  ],

  lastGame: {
    date: "2026-08-11",
    label: "Event 13",
    playerCount: 23,
    kitty: 410,
    winner: "Karey",
    recap: "Karey Koscevic put on a clinic at Event 13, eliminating six straight opponents at the final table. He took down Jeremy early to build a monster stack, then went on a tear: beating Jacob's paired 8s with Aces, sending Phil packing, calling blind against Chris F's 14K shove and hitting a J-4 flush, flushing out Tod's A-2 on the river, and finishing Jake heads-up with Queens over a full house. Six eliminations. All Karey. The OG was on fire. 🔥",
    results: [
      { place: 1,  name: "Karey",   points: 7700, itm: true,  winnings: 600 },
      { place: 2,  name: "Jake",    points: 7000, itm: true,  winnings: 300 },
      { place: 3,  name: "Tod",     points: 6600, itm: true,  winnings: 200 },
      { place: 4,  name: "Chris F", points: 6200, itm: true,  winnings: 100 },
      { place: 5,  name: "Phil",    points: 5800, itm: true,  winnings: 80  },
      { place: 6,  name: "Jacob",   points: 5450, itm: true,  winnings: 40  },
      { place: 7,  name: "Brian",   points: 5100, itm: false, winnings: 0   },
      { place: 8,  name: "Nate",    points: 4800, itm: false, winnings: 0   },
      { place: 9,  name: "Jason",   points: 4500, itm: false, winnings: 0   },
      { place: 10, name: "Tim F",   points: 4200, itm: false, winnings: 0   },
      { place: 11, name: "Chris P", points: 3900, itm: false, winnings: 0   },
      { place: 12, name: "Toner",   points: 3600, itm: false, winnings: 0   },
      { place: 13, name: "JH",      points: 3300, itm: false, winnings: 0   },
      { place: 14, name: "Michael", points: 3000, itm: false, winnings: 0   },
      { place: 15, name: "Eric",    points: 2700, itm: false, winnings: 0   },
      { place: 16, name: "Tom",     points: 2400, itm: false, winnings: 0   },
      { place: 17, name: "Sal",     points: 2100, itm: false, winnings: 0   },
      { place: 18, name: "Steele",  points: 1800, itm: false, winnings: 0   },
      { place: 19, name: "Justin",  points: 1500, itm: false, winnings: 0   },
      { place: 20, name: "Jay",     points: 1200, itm: false, winnings: 0   },
      { place: 21, name: "Jeremy",  points:  900, itm: false, winnings: 0   },
      { place: 22, name: "Matt",    points:  600, itm: false, winnings: 0   },
      { place: 23, name: "Steve",   points:  300, itm: false, winnings: 0   },
    ],
    cashGame: { winner: "", note: "" },
    highHand: { player: "", hand: "", description: "" },
  },

  standings: [
    // Updated from Tod's totals email after Event 13 (2026-08-11)
    { name: "Tod",     fullName: "Tod Ellison",       events: 14, points: 59900, wins: 1, cashes: 5,  avgPlace: 7.8,  avatar: "avatars/tod.png"     },
    { name: "Guy",     fullName: "Guy Caldwell",      events: 10, points: 50200, wins: 2, cashes: 7,  avgPlace: 6.5,  avatar: "avatars/guy.png"     },
    { name: "Jacob",   fullName: "Jacob Bevier",      events: 12, points: 49150, wins: 0, cashes: 5,  avgPlace: 8.2,  avatar: "avatars/jacob.png"   },
    { name: "Michael", fullName: "Michael Curtin",    events: 9,  points: 46600, wins: 0, cashes: 5,  avgPlace: 8.6,  avatar: "avatars/michael.png" },
    { name: "Chris P", fullName: "Chris Pettis",      events: 13, points: 46400, wins: 0, cashes: 5,  avgPlace: 10.2, avatar: "avatars/chris_p.png" },
    { name: "JH",      fullName: "JH Hooper",         events: 11, points: 44400, wins: 2, cashes: 4,  avgPlace: 9.7,  avatar: "avatars/jh.png"      },
    { name: "Karey",   fullName: "Karey Koscevic",    events: 9,  points: 43200, wins: 4, cashes: 5,  avgPlace: 6.2,  avatar: "avatars/karey.png"   },
    { name: "Nate",    fullName: "Nate Woods",        events: 11, points: 41000, wins: 0, cashes: 2,  avgPlace: 10.1, avatar: "avatars/nate.png"    },
    { name: "Chris F", fullName: "Chris Frady",       events: 10, points: 40500, wins: 0, cashes: 4,  avgPlace: 9.0,  avatar: "avatars/chris_f.png" },
    { name: "Steve",   fullName: "Steve Mills",       events: 10, points: 40000, wins: 1, cashes: 3,  avgPlace: 8.7  },
    { name: "Tom",     fullName: "Tom Kane",          events: 11, points: 36400, wins: 0, cashes: 2,  avgPlace: 11.2, avatar: "avatars/tom.png"     },
    { name: "Vince",   fullName: "Vince Ottone",      events: 8,  points: 34500, wins: 0, cashes: 5,  avgPlace: 8.0,  avatar: "avatars/vince.png"   },
    { name: "Philo",   fullName: "Philo Mitman",      events: 13, points: 34200, wins: 0, cashes: 1,  avgPlace: 12.8, avatar: "avatars/philo.png"   },
    { name: "Jeremy",  fullName: "Jeremy Bollinger",  events: 10, points: 33600, wins: 2, cashes: 2,  avgPlace: 12.2, avatar: "avatars/jeremy.png"  },
    { name: "Matt",    fullName: "Matt Therriault",   events: 10, points: 32900, wins: 0, cashes: 0,  avgPlace: 11.7, avatar: "avatars/matt.png"    },
    { name: "Steele",  fullName: "Steele Persons",    events: 12, points: 31300, wins: 0, cashes: 1,  avgPlace: 12.4 },
    { name: "Ryan",    fullName: "Ryan Zondervan",    events: 7,  points: 31250, wins: 0, cashes: 4,  avgPlace: 8.4  },
    { name: "Brian",   fullName: "Brian Reilly",      events: 12, points: 31200, wins: 0, cashes: 0,  avgPlace: 13.5, avatar: "avatars/brian.png"   },
    { name: "Jay",     fullName: "Jay Rose",          events: 10, points: 30100, wins: 1, cashes: 2,  avgPlace: 12.0, avatar: "avatars/jay.png"     },
    { name: "Toner",   fullName: "Tim Toner",         events: 10, points: 30100, wins: 0, cashes: 1,  avgPlace: 12.1, avatar: "avatars/tim_t.png"   },
    { name: "Sal",     fullName: "Chris Salaski",     events: 8,  points: 28500, wins: 0, cashes: 1,  avgPlace: 10.0, avatar: "avatars/sal.png"     },
    { name: "Eric",    fullName: "Eric Cunningham",   events: 13, points: 27300, wins: 0, cashes: 0,  avgPlace: 14.3, avatar: "avatars/eric.png"    },
    { name: "Tim",     fullName: "Tim Fuller",        events: 8,  points: 24600, wins: 0, cashes: 0,  avgPlace: 12.3, avatar: "avatars/tim_f.png"   },
    { name: "Phil",    fullName: "Phil Tricky",       events: 9,  points: 23900, wins: 1, cashes: 3,  avgPlace: 13.0 },
    { name: "Charlie", fullName: "Charlie Grant",     events: 10, points: 23050, wins: 0, cashes: 3,  avgPlace: 14.0, avatar: "avatars/charlie.png" },
    { name: "Jake",    fullName: "Jake Westfall",     events: 6,  points: 23000, wins: 0, cashes: 3,  avgPlace: 10.3, avatar: "avatars/jake_w.png"  },
    { name: "Jason",   fullName: "Jason Oliver",      events: 4,  points: 16800, wins: 0, cashes: 1,  avgPlace: 8.3  },
    { name: "Justin",  fullName: "Justin Harmond",    events: 5,  points:  7100, wins: 0, cashes: 0,  avgPlace: 19.4, avatar: "avatars/justin.png"  },
    { name: "Dom",     fullName: "Dom",               events: 2,  points:  6000, wins: 0, cashes: 0,  avgPlace: 12.5 },
    { name: "Darin",   fullName: "Darin Brewer",      events: 2,  points:  4300, wins: 0, cashes: 0,  avgPlace: 17.0 },
    { name: "Eli",     fullName: "Eli Robbins",       events: 1,  points:  3000, wins: 0, cashes: 0,  avgPlace: 10.0 },
    { name: "James",   fullName: "James",             events: 1,  points:  1800, wins: 0, cashes: 0,  avgPlace: 18.0 },
    { name: "Jeff",    fullName: "Jeff Mennicke",     events: 1,  points:  1200, wins: 0, cashes: 0,  avgPlace: 20.0 },
  ],

  records: {
    highHandAllTime:    { player: "Tod Ellison", hand: "Quad Kings - Ace Kicker", season: 20, date: "" },
    highHandSeason:     { player: "Tod Ellison", hand: "Quad Kings - Ace Kicker", season: 20, date: "" },
    mostWins:           { player: "Tod Ellison", count: 15, note: "Career event wins all-time" },
    mostSeasons:        { player: "Tod Ellison", count: 20, note: "All 20 seasons" },
    mostChampionships:  { player: "JH Hooper & Tod Ellison", count: 2, note: "2x Ardenlee Champions each" },
  },

  champions: [
    { season: 19, year: 2025, champion: "Charlie Grant", note: "First season, first championship" },
    { season: 18, year: 2024, champion: "Eric C",        note: "" },
    { season: 17, year: 2023, champion: "Tod",           note: "" },
    { season: 16, year: 2022, champion: "Chris P",       note: "" },
    { season: 15, year: 2021, champion: "JH",            note: "" },
    { season: 14, year: 2020, champion: "Chris F",       note: "" },
    { season: 13, year: 2019, champion: "Phil",          note: "" },
    { season: 12, year: 2018, champion: "Tom",           note: "" },
    { season: 11, year: 2017, champion: "Vince",         note: "" },
    { season: 10, year: 2016, champion: "Jeremy",        note: "" },
    { season:  9, year: 2015, champion: "Karey",         note: "" },
    { season:  8, year: 2014, champion: "Tod",           note: "" },
    { season:  7, year: 2013, champion: "JH",            note: "" },
    { season:  6, year: 2012, champion: "Buddy",         note: "" },
    { season:  5, year: 2011, champion: "Al",            note: "" },
    { season:  4, year: 2010, champion: "Derek",         note: "" },
    { season:  3, year: 2009, champion: "Sal",           note: "" },
    { season:  2, year: 2008, champion: "",              note: "" },
    { season:  1, year: 2007, champion: "",              note: "" },
  ],

  nextGame: {
    date:      "2026-08-25",
    label:     "Event 14",
    time:      "8:00 PM",
    location:  "Tod's",
    buyin:     40,
    earlyBonus: 500,
    startStack: 6000,
    rebuyStack: 6000,
    maxPlayers: 33,
    notes:     "$40 buy-in, $40 rebuy. 500 early chip bonus.",
  },
};
