/**
 * ARDENLEE POKER LEAGUE - Data File
 * Season 20 | Peachtree City, GA
 * Last updated: after Event 11 (2026-07-02)
 */

const LEAGUE = {
  name: "Ardenlee Poker League",
  season: 20,
  host: "Tod Ellison",
  location: "Peachtree City, GA",

  announcements: [
    { active: true, type: "special", icon: "\u{1F3C6}", text: "Jeremy Bollinger wins Event 11! Next game: July 16th at 8 PM at Tod's. RSVP below!" },
  ],

  schedule: [
    { date: "2026-02-19", label: "Event 1",               type: "regular",    completed: true  },
    { date: "2026-03-05", label: "Event 2",               type: "regular",    completed: true  },
    { date: "2026-03-19", label: "Event 3",               type: "regular",    completed: true  },
    { date: "2026-04-02", label: "Event 4",               type: "regular",    completed: true  },
    { date: "2026-04-16", label: "Event 5",               type: "regular",    completed: true  },
    { date: "2026-04-30", label: "Event 6",               type: "regular",    completed: true  },
    { date: "2026-05-14", label: "Event 7",               type: "regular",    completed: true  },
    { date: "2026-05-19", label: "Event 8",               type: "regular",    completed: true  },
    { date: "2026-06-04", label: "Event 9",               type: "regular",    completed: true  },
    { date: "2026-06-18", label: "Event 10",              type: "regular",    completed: true  },
    { date: "2026-07-02", label: "Event 11",              type: "regular",    completed: true  },
    { date: "2026-07-16", label: "Event 12",              type: "regular",    completed: false },
    { date: "2026-08-01", label: "Mid-Season Tournament", type: "tournament", completed: false },
    { date: "2026-08-11", label: "Event 13",              type: "regular",    completed: false },
    { date: "2026-08-25", label: "Event 14",              type: "regular",    completed: false },
    { date: "2026-09-08", label: "Event 15",              type: "regular",    completed: false },
    { date: "2026-09-22", label: "Season Final",          type: "final",      completed: false },
  ],

  lastGame: {
    date: "2026-07-02",
    label: "Event 11",
    playerCount: 18,
    kitty: 380,
    winner: "Jeremy",
    recap: "Jeremy Bollinger wins Event 11, topping an 18-player field for $500. Tod finished 2nd ($240), Jacob cashed 3rd ($120), Chris P took 4th ($80), and Michael rounded out the money in 5th ($40). Jeremy knocked out Tod heads-up to seal the win.",
    results: [
      { place: 1,  name: "Jeremy",  points: 7000, itm: true,  winnings: 500 },
      { place: 2,  name: "Tod",     points: 5900, itm: true,  winnings: 240 },
      { place: 3,  name: "Jacob",   points: 5400, itm: true,  winnings: 120 },
      { place: 4,  name: "Chris P", points: 4900, itm: true,  winnings: 80  },
      { place: 5,  name: "Michael", points: 4400, itm: true,  winnings: 40  },
      { place: 6,  name: "Philo",   points: 3900, itm: false, winnings: 0   },
      { place: 7,  name: "Ryan",    points: 3600, itm: false, winnings: 0   },
      { place: 8,  name: "Sal",     points: 3300, itm: false, winnings: 0   },
      { place: 9,  name: "Toner",   points: 3000, itm: false, winnings: 0   },
      { place: 10, name: "Tim",     points: 2700, itm: false, winnings: 0   },
      { place: 11, name: "Jay",     points: 2400, itm: false, winnings: 0   },
      { place: 12, name: "Karey",   points: 2100, itm: false, winnings: 0   },
      { place: 13, name: "Tom",     points: 1800, itm: false, winnings: 0   },
      { place: 14, name: "Steele",  points: 1500, itm: false, winnings: 0   },
      { place: 15, name: "Eric",    points: 1200, itm: false, winnings: 0   },
      { place: 16, name: "Phil",    points:  900, itm: false, winnings: 0   },
      { place: 17, name: "Chris F", points:  600, itm: false, winnings: 0   },
    ],
    cashGame: { winner: "", note: "" },
    highHand: { player: "", hand: "", description: "" },
  },

  standings: [
    { name: "Tod",     fullName: "Tod Ellison",       events: 11, points: 47300, wins: 1, cashes: 4,  avgPlace: 7.2,  avatar: "avatars/tod.png"     },
    { name: "Karey",   fullName: "Karey Koscevic",    events: 8,  points: 35800, wins: 3, cashes: 4,  avgPlace: 6.8,  avatar: "avatars/karey.png"   },
    { name: "Guy",     fullName: "Guy Caldwell",      events: 8,  points: 35800, wins: 2, cashes: 5,  avgPlace: 7.4,  avatar: "avatars/guy.png"     },
    { name: "Vince",   fullName: "Vince Ottone",      events: 9,  points: 34500, wins: 0, cashes: 5,  avgPlace: 8.9,  avatar: "avatars/vince.png"   },
    { name: "Jacob",   fullName: "Jacob Bevier",      events: 9,  points: 33800, wins: 0, cashes: 3,  avgPlace: 8.2,  avatar: "avatars/jacob.png"   },
    { name: "Michael", fullName: "Michael Curtin",    events: 6,  points: 32300, wins: 0, cashes: 5,  avgPlace: 8.3,  avatar: "avatars/michael.png" },
    { name: "Chris F", fullName: "Chris Frady",       events: 8,  points: 32200, wins: 0, cashes: 3,  avgPlace: 8.3,  avatar: "avatars/chris_f.png" },
    { name: "JH",      fullName: "JH Hooper",         events: 9,  points: 31700, wins: 2, cashes: 3,  avgPlace: 9.8,  avatar: "avatars/jh.png"      },
    { name: "Steve",   fullName: "Steve Mills",       events: 7,  points: 29700, wins: 1, cashes: 3,  avgPlace: 6.7  },
    { name: "Chris P", fullName: "Chris Pettis",      events: 10, points: 29700, wins: 0, cashes: 3,  avgPlace: 11.3, avatar: "avatars/chris_p.png" },
    { name: "Jay",     fullName: "Jay Rose",          events: 9,  points: 29200, wins: 1, cashes: 2,  avgPlace: 11.0, avatar: "avatars/jay.png"     },
    { name: "Steele",  fullName: "Steele Persons",    events: 10, points: 28300, wins: 0, cashes: 1,  avgPlace: 11.5 },
    { name: "Philo",   fullName: "Philo Mitman",      events: 11, points: 27700, wins: 0, cashes: 1,  avgPlace: 12.6, avatar: "avatars/philo.png"   },
    { name: "Nate",    fullName: "Nate Woods",        events: 9,  points: 25800, wins: 0, cashes: 1,  avgPlace: 10.4, avatar: "avatars/nate.png"    },
    { name: "Tom",     fullName: "Tom Kane",          events: 8,  points: 24100, wins: 0, cashes: 1,  avgPlace: 11.3, avatar: "avatars/tom.png"     },
    { name: "Toner",   fullName: "Tim Toner",         events: 8,  points: 23600, wins: 0, cashes: 1,  avgPlace: 11.4, avatar: "avatars/tim_t.png"   },
    { name: "Matt",    fullName: "Matt Therriault",   events: 7,  points: 23400, wins: 0, cashes: 0,  avgPlace: 10.6 },
    { name: "Eric",    fullName: "Eric Cunningham",   events: 10, points: 23400, wins: 0, cashes: 0,  avgPlace: 12.9, avatar: "avatars/eric.png"    },
    { name: "Ryan",    fullName: "Ryan Zondervan",    events: 6,  points: 23150, wins: 0, cashes: 3,  avgPlace: 9.0  },
    { name: "Jeremy",  fullName: "Jeremy Bollinger",  events: 7,  points: 22900, wins: 1, cashes: 1,  avgPlace: 11.7, avatar: "avatars/jeremy.png"  },
    { name: "Charlie", fullName: "Charlie Grant",     events: 10, points: 22250, wins: 1, cashes: 4,  avgPlace: 11.8, avatar: "avatars/charlie.png" },
    { name: "Sal",     fullName: "Chris Salaski",     events: 5,  points: 18200, wins: 0, cashes: 1,  avgPlace: 8.2,  avatar: "avatars/sal.png"     },
    { name: "Brian",   fullName: "Brian Reilly",      events: 9,  points: 16500, wins: 0, cashes: 0,  avgPlace: 14.2, avatar: "avatars/brian.png"   },
    { name: "Jake",    fullName: "Jake Westfall",     events: 5,  points: 16000, wins: 0, cashes: 2,  avgPlace: 12.0, avatar: "avatars/jake_w.png"  },
    { name: "Tim",     fullName: "Tim Fuller",        events: 4,  points: 12600, wins: 0, cashes: 0,  avgPlace: 11.7, avatar: "avatars/tim_f.png"   },
    { name: "Jason",   fullName: "Jason Oliver",      events: 3,  points: 12300, wins: 0, cashes: 1,  avgPlace: 8.0  },
    { name: "Phil",    fullName: "Phil Tricky",       events: 6,  points: 10300, wins: 0, cashes: 1,  avgPlace: 14.8 },
    { name: "Dom",     fullName: "Dom",               events: 3,  points:  6000, wins: 0, cashes: 1,  avgPlace: 9.0  },
    { name: "Justin",  fullName: "Justin Harmond",    events: 3,  points:  3600, wins: 0, cashes: 0,  avgPlace: 19.3, avatar: "avatars/justin.png"  },
    { name: "James",   fullName: "James",             events: 1,  points:  1800, wins: 0, cashes: 0,  avgPlace: 18.0 },
    { name: "Darin",   fullName: "Darin Brewer",      events: 1,  points:  1500, wins: 0, cashes: 0,  avgPlace: 16.0 },
    { name: "Jeff",    fullName: "Jeff Mennicke",     events: 1,  points:  1200, wins: 0, cashes: 0,  avgPlace: 20.0 },
    { name: "Eli",     fullName: "Eli Robbins",       events: 0,  points:     0, wins: 0, cashes: 0,  avgPlace: 0    },
  ],

  records: {
    highHandAllTime:    { player: "Tod Ellison", hand: "Quad Kings - Ace Kicker", season: 20, date: "" },
    highHandSeason:     { player: "Tod Ellison", hand: "Quad Kings - Ace Kicker", season: 20, date: "" },
    mostWins:           { player: "Tod Ellison", count: 15, note: "Career event wins all-time" },
    mostSeasons:        { player: "Tod Ellison", count: 20, note: "All 20 seasons" },
    mostChampionships:  { player: "JH Hooper & Tod Ellison", count: 2, note: "2x Ardenlee Champions each" },
  },

  champions: [
    { season: 19, year: 2025, champion: "Charlie Grant", note: "First season, first championship" },
    { season: 18, year: 2024, champion: "Eric C",        note: "" },
    { season: 17, year: 2023, champion: "Tod",           note: "" },
    { season: 16, year: 2022, champion: "Chris P",       note: "" },
    { season: 15, year: 2021, champion: "JH",            note: "" },
    { season: 14, year: 2020, champion: "Chris F",       note: "" },
    { season: 13, year: 2019, champion: "Phil",          note: "" },
    { season: 12, year: 2018, champion: "Tom",           note: "" },
    { season: 11, year: 2017, champion: "Vince",         note: "" },
    { season: 10, year: 2016, champion: "Jeremy",        note: "" },
    { season:  9, year: 2015, champion: "Karey",         note: "" },
    { season:  8, year: 2014, champion: "Tod",           note: "" },
    { season:  7, year: 2013, champion: "JH",            note: "" },
    { season:  6, year: 2012, champion: "Buddy",         note: "" },
    { season:  5, year: 2011, champion: "Al",            note: "" },
    { season:  4, year: 2010, champion: "Derek",         note: "" },
    { season:  3, year: 2009, champion: "Sal",           note: "" },
    { season:  2, year: 2008, champion: "",              note: "" },
    { season:  1, year: 2007, champion: "",              note: "" },
  ],

  nextGame: {
    date:      "2026-07-16",
    label:     "Event 12",
    time:      "8:00 PM",
    location:  "Tod's",
    buyin:     20,
    maxPlayers: 20,
  },
};
