/**
 * ARDENLEE POKER LEAGUE - Data File
 * Season 20 | Peachtree City, GA
 * Last updated: after Event 12 (2026-07-16)
 */

const LEAGUE = {
  name: "Ardenlee Poker League",
  season: 20,
  host: "Tod Ellison",
  location: "Peachtree City, GA",

  announcements: [
    { active: true, type: "special", icon: "🏆", text: "Jeremy Bollinger wins the Mid-Season Championship! Next up: Event 13 — August 11th at Tod's. $40 buy-in, $40 rebuy. RSVP below!" },
  ],

  schedule: [
    { date: "2026-02-19", label: "Event 1",               type: "regular",    completed: true  },
    { date: "2026-03-05", label: "Event 2",               type: "regular",    completed: true  },
    { date: "2026-03-19", label: "Event 3",               type: "regular",    completed: true  },
    { date: "2026-04-02", label: "Event 4",               type: "regular",    completed: true  },
    { date: "2026-04-16", label: "Event 5",               type: "regular",    completed: true  },
    { date: "2026-04-30", label: "Event 6",               type: "regular",    completed: true  },
    { date: "2026-05-14", label: "Event 7",               type: "regular",    completed: true  },
    { date: "2026-05-19", label: "Event 8",               type: "regular",    completed: true  },
    { date: "2026-06-04", label: "Event 9",               type: "regular",    completed: true  },
    { date: "2026-06-18", label: "Event 10",              type: "regular",    completed: true  },
    { date: "2026-07-02", label: "Event 11",              type: "regular",    completed: true  },
    { date: "2026-07-16", label: "Event 12",              type: "regular",    completed: true  },
    { date: "2026-07-25", label: "Mid-Season Tournament", type: "tournament", completed: true  },
    { date: "2026-08-11", label: "Event 13",              type: "regular",    completed: false },
    { date: "2026-08-25", label: "Event 14",              type: "regular",    completed: false },
    { date: "2026-09-08", label: "Event 15",              type: "regular",    completed: false },
    { date: "2026-09-22", label: "Season Final",          type: "final",      completed: false },
  ],

  lastGame: {
    date: "2026-07-25",
    label: "Mid-Season Tournament",
    playerCount: 23,
    kitty: 900,
    winner: "Jeremy",
    recap: "Jeremy Bollinger wins the Mid-Season Championship, topping a 23-player field for $640. Guy Caldwell finished 2nd ($320), Jacob Bevier 3rd ($200), Nate Woods 4th ($120), Ryan Zondervan 5th ($80), and Chris P 6th ($40). Phil also took home the $50 Toner's Game prize by drawing Jeremy from the hat.",
    results: [
      { place: 1,  name: "Jeremy",  points: 8000, itm: true,  winnings: 640 },
      { place: 2,  name: "Guy",     points: 7400, itm: true,  winnings: 320 },
      { place: 3,  name: "Jacob",   points: 7000, itm: true,  winnings: 200 },
      { place: 4,  name: "Nate",    points: 6600, itm: true,  winnings: 120 },
      { place: 5,  name: "Ryan",    points: 6200, itm: true,  winnings: 80  },
      { place: 6,  name: "Chris P", points: 5800, itm: true,  winnings: 40  },
      { place: 7,  name: "Michael", points: 5400, itm: false, winnings: 0   },
      { place: 8,  name: "Matt",    points: 5100, itm: false, winnings: 0   },
      { place: 9,  name: "Steve",   points: 4800, itm: false, winnings: 0   },
      { place: 10, name: "Tim",     points: 4500, itm: false, winnings: 0   },
      { place: 11, name: "Philo",   points: 4200, itm: false, winnings: 0   },
      { place: 12, name: "Sal",     points: 3900, itm: false, winnings: 0   },
      { place: 13, name: "JH",      points: 3600, itm: false, winnings: 0   },
      { place: 14, name: "Tom",     points: 3300, itm: false, winnings: 0   },
      { place: 15, name: "Tod",     points: 3000, itm: false, winnings: 0   },
      { place: 16, name: "Brian",   points: 2700, itm: false, winnings: 0   },
      { place: 17, name: "Toner",   points: 2400, itm: false, winnings: 0   },
      { place: 18, name: "Darin",   points: 2100, itm: false, winnings: 0   },
      { place: 19, name: "Chris F", points: 1800, itm: false, winnings: 0   },
      { place: 20, name: "Justin",  points: 1500, itm: false, winnings: 0   },
      { place: 21, name: "Phil",    points: 1200, itm: false, winnings: 50  },
      { place: 22, name: "Eric",    points:  900, itm: false, winnings: 0   },
      { place: 23, name: "Charlie", points:  600, itm: false, winnings: 0   },
    ],
    cashGame: { winner: "", note: "" },
    highHand: { player: "", hand: "", description: "" },
  },

  standings: [
    // Mid-Season Championship added (2026-07-25, 23 players)
    { name: "Tod",     fullName: "Tod Ellison",       events: 13, points: 51900, wins: 1, cashes: 4,  avgPlace: 8.2,  avatar: "avatars/tod.png"     },
    { name: "Guy",     fullName: "Guy Caldwell",      events: 10, points: 48200, wins: 2, cashes: 7,  avgPlace: 6.5,  avatar: "avatars/guy.png"     },
    { name: "Michael", fullName: "Michael Curtin",    events: 8,  points: 41700, wins: 0, cashes: 5,  avgPlace: 7.9,  avatar: "avatars/michael.png" },
    { name: "Jacob",   fullName: "Jacob Bevier",      events: 11, points: 41400, wins: 0, cashes: 4,  avgPlace: 8.4,  avatar: "avatars/jacob.png"   },
    { name: "Chris P", fullName: "Chris Pettis",      events: 12, points: 40500, wins: 0, cashes: 5,  avgPlace: 10.1, avatar: "avatars/chris_p.png" },
    { name: "JH",      fullName: "JH Hooper",         events: 10, points: 39900, wins: 2, cashes: 4,  avgPlace: 9.4,  avatar: "avatars/jh.png"      },
    { name: "Steve",   fullName: "Steve Mills",       events: 9,  points: 38100, wins: 1, cashes: 3,  avgPlace: 7.1  },
    { name: "Karey",   fullName: "Karey Koscevic",    events: 8,  points: 35500, wins: 3, cashes: 4,  avgPlace: 6.9,  avatar: "avatars/karey.png"   },
    { name: "Vince",   fullName: "Vince Ottone",      events: 8,  points: 34500, wins: 0, cashes: 5,  avgPlace: 8.0,  avatar: "avatars/vince.png"   },
    { name: "Nate",    fullName: "Nate Woods",        events: 10, points: 34200, wins: 0, cashes: 2,  avgPlace: 10.3, avatar: "avatars/nate.png"    },
    { name: "Chris F", fullName: "Chris Frady",       events: 9,  points: 33700, wins: 0, cashes: 3,  avgPlace: 9.6,  avatar: "avatars/chris_f.png" },
    { name: "Tom",     fullName: "Tom Kane",          events: 10, points: 32900, wins: 0, cashes: 2,  avgPlace: 10.8, avatar: "avatars/tom.png"     },
    { name: "Philo",   fullName: "Philo Mitman",      events: 13, points: 32800, wins: 0, cashes: 1,  avgPlace: 12.8, avatar: "avatars/philo.png"   },
    { name: "Matt",    fullName: "Matt Therriault",   events: 9,  points: 30600, wins: 0, cashes: 0,  avgPlace: 10.6, avatar: "avatars/matt.png"    },
    { name: "Jeremy",  fullName: "Jeremy Bollinger",  events: 9,  points: 29900, wins: 2, cashes: 2,  avgPlace: 11.2, avatar: "avatars/jeremy.png"  },
    { name: "Steele",  fullName: "Steele Persons",    events: 11, points: 29500, wins: 0, cashes: 1,  avgPlace: 11.9 },
    { name: "Ryan",    fullName: "Ryan Zondervan",    events: 7,  points: 29350, wins: 0, cashes: 4,  avgPlace: 8.4  },
    { name: "Jay",     fullName: "Jay Rose",          events: 9,  points: 28900, wins: 1, cashes: 2,  avgPlace: 11.1, avatar: "avatars/jay.png"     },
    { name: "Toner",   fullName: "Tim Toner",         events: 9,  points: 25700, wins: 0, cashes: 1,  avgPlace: 12.1, avatar: "avatars/tim_t.png"   },
    { name: "Brian",   fullName: "Brian Reilly",      events: 11, points: 25200, wins: 0, cashes: 0,  avgPlace: 14.1, avatar: "avatars/brian.png"   },
    { name: "Sal",     fullName: "Chris Salaski",     events: 7,  points: 25100, wins: 0, cashes: 1,  avgPlace: 9.0,  avatar: "avatars/sal.png"     },
    { name: "Eric",    fullName: "Eric Cunningham",   events: 12, points: 24300, wins: 0, cashes: 0,  avgPlace: 14.2, avatar: "avatars/eric.png"    },
    { name: "Tim",     fullName: "Tim Fuller",        events: 8,  points: 23100, wins: 0, cashes: 0,  avgPlace: 12.3, avatar: "avatars/tim_f.png"   },
    { name: "Charlie", fullName: "Charlie Grant",     events: 10, points: 22850, wins: 0, cashes: 3,  avgPlace: 14.0, avatar: "avatars/charlie.png" },
    { name: "Phil",    fullName: "Phil Tricky",       events: 8,  points: 17700, wins: 1, cashes: 2,  avgPlace: 14.0 },
    { name: "Jake",    fullName: "Jake Westfall",     events: 5,  points: 16000, wins: 0, cashes: 2,  avgPlace: 12.0, avatar: "avatars/jake_w.png"  },
    { name: "Jason",   fullName: "Jason Oliver",      events: 3,  points: 12300, wins: 0, cashes: 1,  avgPlace: 8.0  },
    { name: "Dom",     fullName: "Dom",               events: 2,  points:  6000, wins: 0, cashes: 0,  avgPlace: 12.5 },
    { name: "Justin",  fullName: "Justin Harmond",    events: 4,  points:  5100, wins: 0, cashes: 0,  avgPlace: 19.5, avatar: "avatars/justin.png"  },
    { name: "Darin",   fullName: "Darin Brewer",      events: 2,  points:  3600, wins: 0, cashes: 0,  avgPlace: 17.0 },
    { name: "Eli",     fullName: "Eli Robbins",       events: 1,  points:  3000, wins: 0, cashes: 0,  avgPlace: 10.0 },
    { name: "James",   fullName: "James",             events: 1,  points:  1800, wins: 0, cashes: 0,  avgPlace: 18.0 },
    { name: "Jeff",    fullName: "Jeff Mennicke",     events: 1,  points:  1200, wins: 0, cashes: 0,  avgPlace: 20.0 },
  ],

  records: {
    highHandAllTime:    { player: "Tod Ellison", hand: "Quad Kings - Ace Kicker", season: 20, date: "" },
    highHandSeason:     { player: "Tod Ellison", hand: "Quad Kings - Ace Kicker", season: 20, date: "" },
    mostWins:           { player: "Tod Ellison", count: 15, note: "Career event wins all-time" },
    mostSeasons:        { player: "Tod Ellison", count: 20, note: "All 20 seasons" },
    mostChampionships:  { player: "JH Hooper & Tod Ellison", count: 2, note: "2x Ardenlee Champions each" },
  },

  champions: [
    { season: 19, year: 2025, champion: "Charlie Grant", note: "First season, first championship" },
    { season: 18, year: 2024, champion: "Eric C",        note: "" },
    { season: 17, year: 2023, champion: "Tod",           note: "" },
    { season: 16, year: 2022, champion: "Chris P",       note: "" },
    { season: 15, year: 2021, champion: "JH",            note: "" },
    { season: 14, year: 2020, champion: "Chris F",       note: "" },
    { season: 13, year: 2019, champion: "Phil",          note: "" },
    { season: 12, year: 2018, champion: "Tom",           note: "" },
    { season: 11, year: 2017, champion: "Vince",         note: "" },
    { season: 10, year: 2016, champion: "Jeremy",        note: "" },
    { season:  9, year: 2015, champion: "Karey",         note: "" },
    { season:  8, year: 2014, champion: "Tod",           note: "" },
    { season:  7, year: 2013, champion: "JH",            note: "" },
    { season:  6, year: 2012, champion: "Buddy",         note: "" },
    { season:  5, year: 2011, champion: "Al",            note: "" },
    { season:  4, year: 2010, champion: "Derek",         note: "" },
    { season:  3, year: 2009, champion: "Sal",           note: "" },
    { season:  2, year: 2008, champion: "",              note: "" },
    { season:  1, year: 2007, champion: "",              note: "" },
  ],

  nextGame: {
    date:      "2026-08-11",
    label:     "Event 13",
    time:      "5:00 PM",
    location:  "Tod's",
    buyin:     40,
    earlyBonus: 500,
    startStack: 6000,
    rebuyStack: 6000,
    maxPlayers: 33,
    notes:     "$40 buy-in, $40 rebuy. 500 early chip bonus.",
  },
};
